version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0

  pre_build:
    commands:
      - dotnet restore AWSCodePipelineDemo/AWSCodePipelineDemo.csproj

  build:
    commands:
      - dotnet build AWSCodePipelineDemo/AWSCodePipelineDemo.csproj

  post_build:
    commands:
      - dotnet publish AWSCodePipelineDemo/AWSCodePipelineDemo.csproj -c Release -o ./app

artifacts:
  files:
    - '**/*'
  base-directory: './app'